"""
portal_nav — Atlas pipeline generator

Reads all service entities and produces apps/dashboard/portal-nav.json,
which portal.html fetches instead of using a hardcoded services array.

Output shape:
{
  "generated_at": "2026-05-18T16:30:00Z",
  "groups": [
    {
      "group": "Ops",
      "items": [
        {
          "id": "home-command",
          "label": "Home Command",
          "url": "https://home.example.com",
          "port": 8094,
          "key": "home-command"
        }
      ]
    }
  ]
}

Selection rules:
  - lifecycle == vocab:service_lifecycles:running
  - portal_visible == true
  - URL resolved in priority order: portal_url > external_url > portal_path
    (portal_path is relative to portal origin, e.g. /s/example-app)

Grouping: tier field maps to group label.
  ops -> Ops, media -> Media, games -> Games, apps -> Apps
  unknown/missing tier -> Other

Ordering: groups follow TIER_ORDER; items within a group are sorted by label.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from schemas.service import Service

NAME = "portal_nav"
INPUTS = ["service:*"]
OUTPUTS = [
    "outputs/dashboard/portal-nav.json"
]

# Group display names and render order
TIER_ORDER = ["ops", "media", "games", "apps"]
TIER_LABELS = {
    "ops": "Ops",
    "media": "Media",
    "games": "Games",
    "apps": "Apps",
}

RUNNING = "vocab:service_lifecycles:running"
MAINTAINED = "vocab:service_lifecycles:maintained"
# portal_visible: true services with these lifecycles are included.
# retired + concept are always excluded (not accessible or not deployed).
PORTAL_LIFECYCLES = {RUNNING, MAINTAINED}


def _resolve_url(svc: Service) -> str | None:
    """Return the URL to use in the portal iframe for this service."""
    if svc.portal_url:
        return svc.portal_url
    if svc.external_url:
        return svc.external_url
    if svc.portal_path:
        return svc.portal_path
    return None


def generate(store: dict) -> dict[str, str]:
    import json

    services_store = store.get("service", {})
    services: list[Service] = [
        s for s in services_store.values()
        if isinstance(s, Service)
    ]

    # Filter: running/maintained + portal_visible
    visible = [
        s for s in services
        if str(s.lifecycle) in PORTAL_LIFECYCLES and s.portal_visible is True
    ]

    # Build group -> items map
    groups: dict[str, list[dict[str, Any]]] = {t: [] for t in TIER_ORDER}
    groups["other"] = []

    for svc in visible:
        url = _resolve_url(svc)
        if not url:
            # portal_visible: true but no URL — skip with a comment in output
            continue

        tier = (svc.tier or "other").lower()
        group_key = tier if tier in TIER_ORDER else "other"

        item: dict[str, Any] = {
            "id": svc.id,
            "label": svc.portal_label or svc.name,
            "url": url,
        }
        if svc.port:
            item["port"] = svc.port
        # key used by portal.html for auth-gate RBAC visibility filtering
        item["key"] = svc.id

        groups[group_key].append(item)

    # Sort items within each group by label
    for key in groups:
        groups[key].sort(key=lambda x: x["label"].lower())

    # Build ordered group list, omitting empty groups
    group_list = []
    for tier in TIER_ORDER:
        if groups[tier]:
            group_list.append({
                "group": TIER_LABELS[tier],
                "items": groups[tier],
            })
    if groups["other"]:
        group_list.append({
            "group": "Other",
            "items": groups["other"],
        })

    # Drift check: portal_visible=true but no URL resolved — these are gaps.
    gaps = []
    for svc in visible:
        if not _resolve_url(svc):
            gaps.append({
                "id": svc.id,
                "name": svc.name,
                "reason": "portal_visible: true but external_url, portal_url, and portal_path all unset",
            })

    # Also flag running services with no portal_visible set at all (unclassified).
    unclassified = [
        {"id": svc.id, "name": svc.name, "reason": "portal_visible not set on running service"}
        for svc in services
        if str(svc.lifecycle) in PORTAL_LIFECYCLES and svc.portal_visible is None
        and (svc.external_url or svc.portal_path or svc.portal_url)
    ]

    output = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generator": NAME,
        "note": "AUTO-GENERATED by Atlas portal_nav generator. Do not hand-edit.",
        "groups": group_list,
        "integrity": {
            "gaps": gaps,
            "unclassified": sorted(unclassified, key=lambda x: x["id"]),
        },
    }

    return {
        OUTPUTS[0]: json.dumps(output, indent=2) + "\n",
    }
