from __future__ import annotations

"""remediate.py — dispatch DriftRecord list to auto/propose/flag actions.

auto   → execute immediately (safe file operations only; no entity creation)
propose → write stub YAML to atlas-store/staging/<id>.yaml for operator review
flag   → collect into returned flag list; no writes

Usage (CLI):
    python tools/remediate.py              # execute (auto), write stubs (propose), print flags
    python tools/remediate.py --dry-run    # show what would happen, write nothing
    python tools/remediate.py --tier auto  # only execute auto-tier actions
"""

import os
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
SERVICES_ROOT = Path(".")

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.atlas_lock import atlas_write_lock
from tools.drift import DriftRecord

_STAGING_DIR = REPO_ROOT / "staging"

_GIT_ENV = {
    **os.environ,
    "GIT_AUTHOR_NAME": "atlas-drift",
    "GIT_COMMITTER_NAME": "atlas-drift",
    "GIT_AUTHOR_EMAIL": "atlas@example.local",
    "GIT_COMMITTER_EMAIL": "atlas@example.local",
}


def _git_commit_services(paths: list[str], message: str) -> dict[str, Any]:
    for rel_path in paths:
        add = subprocess.run(
            ["git", "add", rel_path],
            cwd=str(SERVICES_ROOT),
            capture_output=True,
            text=True,
            timeout=10,
        )
        if add.returncode != 0:
            return {"error": f"git add {rel_path} failed: {add.stderr.strip()}"}

    commit = subprocess.run(
        ["git", "commit", "-m", message, "--", *paths],
        cwd=str(SERVICES_ROOT),
        capture_output=True,
        text=True,
        timeout=15,
        env=_GIT_ENV,
    )
    if commit.returncode != 0:
        stderr = commit.stderr.strip()
        if "nothing to commit" in commit.stdout or "nothing to commit" in stderr:
            return {"ok": True, "sha": "", "note": "nothing to commit"}
        return {"error": f"git commit failed: {stderr}"}
    return {"ok": True, "sha": commit.stdout.strip().split()[-1] if commit.stdout.strip() else ""}


def _git_commit_atlas(paths: list[str], message: str) -> dict[str, Any]:
    # Serialized against the MCP server + retention sweep and committed with an
    # explicit pathspec so a concurrent atlas-store write can't ride along.
    with atlas_write_lock(REPO_ROOT):
        for rel_path in paths:
            add = subprocess.run(
                ["git", "add", rel_path],
                cwd=str(REPO_ROOT),
                capture_output=True,
                text=True,
                timeout=10,
            )
            if add.returncode != 0:
                return {"error": f"git add {rel_path} failed: {add.stderr.strip()}"}

        commit = subprocess.run(
            ["git", "commit", "-m", message, "--", *paths],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
            timeout=15,
            env=_GIT_ENV,
        )
        if commit.returncode != 0:
            stderr = commit.stderr.strip()
            if "nothing to commit" in commit.stdout or "nothing to commit" in stderr:
                return {"ok": True, "sha": "", "note": "nothing to commit"}
            return {"error": f"git commit failed: {stderr}"}
        return {"ok": True, "sha": commit.stdout.strip().split()[-1] if commit.stdout.strip() else ""}


def _stub_project_yaml(dir_name: str, norm_id: str) -> str:
    return f"""\
# OPERATOR-REVIEW: stub generated by atlas-drift remediation
# Promote to entities/projects/{norm_id}.yaml when complete.
# Source: kb/Projects directory '{dir_name}' exists with no entity.
id: {norm_id}
name: {dir_name}
summary: |
  Stub — operator to fill in.
category: vocab:lifecycle_categories:current
status: vocab:project_statuses:concept
concept_doc: docs/kb/Projects/{dir_name}/10-CONCEPT/{norm_id.upper().replace('-', '_')}_CONCEPT.md
created_at: 2026-05-10T00:00:00Z
updated_at: 2026-05-10T00:00:00Z
"""


def _stub_service_yaml(service_key: str) -> str:
    return f"""\
# OPERATOR-REVIEW: stub generated by atlas-drift remediation
# Promote to entities/services/{service_key}.yaml when complete.
# Source: '{service_key}' exists in catalog.json but has no atlas-store entity.
id: {service_key}
name: {service_key.replace('-', ' ').title()}
summary: |
  Stub — operator to fill in.
service_type: vocab:service_types:docker_container
lifecycle: vocab:service_lifecycles:running
host: server:hydra
deployment_path: .
owned_by: project:{service_key}
created_at: 2026-05-10T00:00:00Z
updated_at: 2026-05-10T00:00:00Z
"""


RemediationResult = dict[str, Any]


def remediate(
    records: list[DriftRecord],
    dry_run: bool = False,
    tiers: set[str] | None = None,
) -> dict[str, list[RemediationResult]]:
    """Dispatch drift records to actions. Returns results by tier.

    tiers: if provided, only process these tiers (e.g. {"auto"})
    """
    if tiers is None:
        tiers = {"auto", "propose", "flag"}

    results: dict[str, list[RemediationResult]] = {"auto": [], "propose": [], "flag": []}

    auto_deleted: list[str] = []
    staging_written: list[str] = []

    for record in records:
        if record.fix_tier not in tiers:
            continue

        if record.fix_tier == "auto":
            if record.kind == "orphaned_output_file":
                file_path = Path(record.extra.get("path", ""))
                if dry_run:
                    results["auto"].append({"action": "delete", "path": str(file_path), "dry_run": True})
                else:
                    if file_path.exists():
                        file_path.unlink()
                        auto_deleted.append(str(file_path.relative_to(SERVICES_ROOT)))
                        results["auto"].append({"action": "deleted", "path": str(file_path)})
                    else:
                        results["auto"].append({"action": "skip_missing", "path": str(file_path)})
            else:
                results["auto"].append({"action": "unhandled_auto_kind", "kind": record.kind, "id": record.id})

        elif record.fix_tier == "propose":
            if record.kind == "kb_orphan_dir":
                stub_path = _STAGING_DIR / f"{record.normalized_id}.yaml"
                if dry_run:
                    results["propose"].append({"action": "write_stub", "path": str(stub_path), "dry_run": True, "kind": "project"})
                else:
                    _STAGING_DIR.mkdir(exist_ok=True)
                    stub_path.write_text(_stub_project_yaml(record.id, record.normalized_id), encoding="utf-8")
                    staging_written.append(f"staging/{stub_path.name}")
                    results["propose"].append({"action": "wrote_stub", "path": str(stub_path), "kind": "project"})

            elif record.kind in ("catalog_only_service", "sot_service_not_in_atlas"):
                stub_path = _STAGING_DIR / f"{record.id}.yaml"
                if dry_run:
                    results["propose"].append({"action": "write_stub", "path": str(stub_path), "dry_run": True, "kind": "service"})
                else:
                    _STAGING_DIR.mkdir(exist_ok=True)
                    stub_path.write_text(_stub_service_yaml(record.id), encoding="utf-8")
                    staging_written.append(f"staging/{stub_path.name}")
                    results["propose"].append({"action": "wrote_stub", "path": str(stub_path), "kind": "service"})
            else:
                results["propose"].append({"action": "unhandled_propose_kind", "kind": record.kind, "id": record.id})

        elif record.fix_tier == "flag":
            results["flag"].append({"id": record.id, "kind": record.kind, "detail": record.detail})

    # Commit auto deletions (services repo)
    if not dry_run and auto_deleted:
        commit_result = _git_commit_services(
            auto_deleted,
            f"drift: auto-delete {len(auto_deleted)} orphaned output file(s)",
        )
        results["auto"].append({"commit": commit_result})

    # Commit staging stubs (atlas-store)
    if not dry_run and staging_written:
        commit_result = _git_commit_atlas(
            staging_written,
            f"drift: propose {len(staging_written)} stub(s) for operator review",
        )
        results["propose"].append({"commit": commit_result})

    return results


if __name__ == "__main__":
    from tools.drift_runner import collect_all

    dry_run = "--dry-run" in sys.argv
    tier_arg = None
    if "--tier" in sys.argv:
        idx = sys.argv.index("--tier")
        if idx + 1 < len(sys.argv):
            tier_arg = {sys.argv[idx + 1]}

    records = collect_all()
    print(f"Drift records: {len(records)} ({sum(1 for r in records if r.fix_tier == 'auto')} auto, "
          f"{sum(1 for r in records if r.fix_tier == 'propose')} propose, "
          f"{sum(1 for r in records if r.fix_tier == 'flag')} flag)")
    if dry_run:
        print("DRY RUN — no writes")

    results = remediate(records, dry_run=dry_run, tiers=tier_arg)

    for tier, items in results.items():
        if items:
            print(f"\n[{tier.upper()}]")
            for item in items:
                print(f"  {item}")
